import{useState}from'react';
import{api,json}from'./lib/api';
import{type BrandRecord,type ClientInput,type ClientRecord}from'../shared/model';

function Field({label,value,onChange,type='text',full=false}:{label:string,value:string,onChange:(v:string)=>void,type?:string,full?:boolean}){return <div className={'field '+(full?'full':'')}><label>{label}</label><input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Area({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){return <div className="field full"><label>{label}</label><textarea className="textarea" value={value} onChange={e=>onChange(e.target.value)}/></div>}
const blank=():ClientInput=>({name:'',tradingName:'',abn:'',contact:'',email:'',phone:'',address:'',website:'',defaultBrandId:'',currency:'AUD',paymentTerms:'',validityDays:30,notes:'',tags:[],accountManager:'',archived:false});
const input=(c:ClientRecord):ClientInput=>({name:c.name,tradingName:c.tradingName,abn:c.abn,contact:c.contact,email:c.email,phone:c.phone,address:c.address,website:c.website,defaultBrandId:c.defaultBrandId,currency:c.currency,paymentTerms:c.paymentTerms,validityDays:c.validityDays,notes:c.notes,tags:c.tags,accountManager:c.accountManager,archived:c.archived});

export function ClientManager({clients,brands,onChanged}:{clients:ClientRecord[];brands:BrandRecord[];onChanged:()=>Promise<void>}){
 const[selected,setSelected]=useState(''),[draft,setDraft]=useState<ClientInput>(blank()),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const choose=(c?:ClientRecord)=>{setSelected(c?.id||'');setDraft(c?input(c):blank());setMessage('')};
 const set=<K extends keyof ClientInput>(key:K,value:ClientInput[K])=>setDraft(x=>({...x,[key]:value}));
 const save=async()=>{setBusy(true);setMessage('');try{const saved=selected?await api<ClientRecord>('/clients/'+selected,{method:'PUT',body:json(draft)}):await api<ClientRecord>('/clients',{method:'POST',body:json(draft)});await onChanged();choose(saved);setMessage('Client saved.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 return <div className="master-grid"><section className="card master-list"><div className="master-head"><h2>Clients</h2><button className="btn primary" onClick={()=>choose()}>New client</button></div>{clients.map(c=><button key={c.id} className={'master-row '+(selected===c.id?'active':'')} onClick={()=>choose(c)}><span><strong>{c.name}</strong><small>{c.contact||'No contact'}{c.archived?' · archived':''}</small></span></button>)}</section><section className="card master-edit"><h2>{selected?'Edit client':'New client'}</h2>{message&&<div className="banner">{message}</div>}<div className="fields"><Field label="Organisation" value={draft.name} onChange={v=>set('name',v)}/><Field label="Trading name" value={draft.tradingName} onChange={v=>set('tradingName',v)}/><Field label="ABN / identifier" value={draft.abn} onChange={v=>set('abn',v)}/><Field label="Primary contact" value={draft.contact} onChange={v=>set('contact',v)}/><Field label="Email" value={draft.email} onChange={v=>set('email',v)}/><Field label="Phone" value={draft.phone} onChange={v=>set('phone',v)}/><Field label="Website" value={draft.website} onChange={v=>set('website',v)}/><Field label="Account manager" value={draft.accountManager} onChange={v=>set('accountManager',v)}/><Field label="Address" full value={draft.address} onChange={v=>set('address',v)}/><div className="field"><label>Default brand</label><select className="select" value={draft.defaultBrandId} onChange={e=>set('defaultBrandId',e.target.value)}><option value="">None</option>{brands.filter(b=>!b.archived).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className="field"><label>Currency</label><select className="select" value={draft.currency} onChange={e=>set('currency',e.target.value as ClientInput['currency'])}>{['AUD','NZD','USD','GBP','EUR'].map(x=><option key={x}>{x}</option>)}</select></div><Field label="Proposal validity (days)" type="number" value={String(draft.validityDays)} onChange={v=>set('validityDays',Math.max(0,Number(v)||0))}/><Field label="Tags (comma separated)" value={draft.tags.join(', ')} onChange={v=>set('tags',v.split(',').map(x=>x.trim()).filter(Boolean))}/><Area label="Payment terms" value={draft.paymentTerms} onChange={v=>set('paymentTerms',v)}/><Area label="Internal notes" value={draft.notes} onChange={v=>set('notes',v)}/><div className="field full"><label><input type="checkbox" checked={draft.archived} onChange={e=>set('archived',e.target.checked)}/> Archived</label></div></div><button className="btn primary" disabled={busy||!draft.name.trim()} onClick={save}>Save client</button></section></div>
}
