import{useMemo,useState}from'react';
import{api,json}from'./lib/api';
import{type BrandRecord,type ClientRecord,type DocumentRecord,type TemplateRecord}from'../shared/model';

export function CreateWizard({brands,clients,templates,onCreated}:{brands:BrandRecord[];clients:ClientRecord[];templates:TemplateRecord[];onCreated:(d:DocumentRecord)=>void}){
 const[brandId,setBrandId]=useState(''),[clientId,setClientId]=useState(''),[templateId,setTemplateId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const activeBrands=brands.filter(x=>!x.archived),activeClients=clients.filter(x=>!x.archived);
 const available=useMemo(()=>templates.filter(t=>t.active&&(!t.brandId||t.brandId===brandId)&&(!t.clientId||t.clientId===clientId)),[templates,brandId,clientId]);
 const chooseClient=(id:string)=>{setClientId(id);setTemplateId('');const c=clients.find(x=>x.id===id);if(c?.defaultBrandId)setBrandId(c.defaultBrandId)};
 const create=async()=>{if(!brandId||!clientId||!templateId)return;setBusy(true);setMessage('');try{onCreated(await api<DocumentRecord>('/documents/from-template',{method:'POST',body:json({brandId,clientId,templateId})}))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 return <div className="wizard card"><div className="wizard-head"><h2>Create document</h2><p className="muted">Select the reusable records that will be snapshotted into the new draft.</p></div>{message&&<div className="banner">{message}</div>}<div className="wizard-step"><span>1</span><div className="field"><label>Brand</label><select className="select" value={brandId} onChange={e=>{setBrandId(e.target.value);setTemplateId('')}}><option value="">Select brand</option>{activeBrands.map(b=><option key={b.id} value={b.id}>{b.name} · {b.type}</option>)}</select></div></div><div className="wizard-step"><span>2</span><div className="field"><label>Client</label><select className="select" value={clientId} onChange={e=>chooseClient(e.target.value)}><option value="">Select client</option>{activeClients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div><div className="wizard-step"><span>3</span><div className="field"><label>Template</label><select className="select" value={templateId} onChange={e=>setTemplateId(e.target.value)} disabled={!brandId||!clientId}><option value="">Select template</option>{available.map(t=><option key={t.id} value={t.id}>{t.name}{t.clientId?' · client variant':''} · v{t.version}</option>)}</select>{brandId&&clientId&&!available.length&&<small className="muted">No compatible active templates. Create one in Template Manager.</small>}</div></div><div className="wizard-summary"><strong>Document snapshot</strong><p className="muted">The new draft will retain the selected brand, client and template version even if those master records are changed later.</p></div><button className="btn primary" disabled={!brandId||!clientId||!templateId||busy} onClick={create}>{busy?'Creating…':'Create draft'}</button></div>
}
